include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = Freedom

Freedom_FILES = FDPRootListController.m
Freedom_LIBRARIES = applist
Freedom_FRAMEWORKS = UIKit
Freedom_PRIVATE_FRAMEWORKS = Preferences
Freedom_INSTALL_PATH = /Library/PreferenceBundles
Freedom_CFLAGS = -fobjc-arc

include $(THEOS_MAKE_PATH)/bundle.mk
